### ISSUE TITLE
Serial input issue

### ISSUE THREAD

**Issue by Hesstre** [duinoapp/duinoapp-client#16]
Hey! Im trying to use chromeduino 3 with my  arduino nano, and im getting some issues with the serial input. My arduino/USB is getting dected and I can click connect and pair it but it  doesent seem to affect anything. I checked on my pc and all the settings in chromduino are the same as the Arduino IDE ones:( arduino nano and ATmega 328p (old bootloader)) so im not sure whats the problem. If anyone could help that would be great

**Comment by mrfrase3** [comment]
Have you previously been successful at programming that Arduino with the Arduino IDE?

**Comment by mrfrase3** [comment]
Hey, just pinging you on this, otherwise, I'll close this ticket. (maybe try not the old bootloader)
