### ISSUE TITLE
Cannot add servers

### ISSUE THREAD

**Issue by MrWollenburg** [duinoapp/duinoapp-client#23]
I tried added a few of the old Duino 2 servers and it appears none of them can connect, even though their URLs are active.

![Screenshot 2021-04-23 7 38 56 AM](https://user-images.githubusercontent.com/83072991/115872205-26f13380-a407-11eb-91a8-135b89488c12.png)

**Comment by mrfrase3** [comment]
Hey,

With a change in protocol, the old servers from chromeduino 2 are not compatible with version 3 (new v3 servers should be backwards compatible)

Are you having issues with the new compile server? Or are you running your own?

The old servers were flaky with their stability, the new ones should be a lot better

**Comment by MrWollenburg** [comment]
> Hey,
> 
> With a change in protocol, the old servers from chromeduino 2 are not compatible with version 3 (new v3 servers should be backwards compatible)
> 
> Are you having issues with the new compile server? Or are you running your own?
> 
> The old servers were flaky with their stability, the new ones should be a lot better

Makes sense! I was using old v2 servers. I'll wait for the potential 50% issue to get fixed.  :)  Keep up the great work!

**Comment by mrfrase3** [comment]
Thanks! Will do! :+1:
