### ISSUE TITLE
More Editor Settings

### ISSUE THREAD

**Issue by mrfrase3** [duinoapp/duinoapp-client#5]
Add more editor settings to allow people to configure the editor how they prefer.

I'm mainly adding font size, as it is an accessability feature, and a few other options. If there are other options people want me to expose, it's pretty straight forward, they just need to open a ticket.

To request an editor setting:
1. Make sure the option is [on this list](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html)
2. Make sure there is [no existing ticket requesting the option.](https://github.com/duinoapp/duinoapp-client/issues?q=is%3Aissue+label%3Asetting)
3. Open a ticket requesting the feature.

**Comment by EDBCREPO** [comment]
- minimap enable
- indentation size
