### ISSUE TITLE
Mouse issue

### ISSUE THREAD

**Issue by ghost** [duinoapp/duinoapp-client#68]
I am working on an autoclicker and I noiticed there was an error when I tried to upload it. There are some screenshots of the code and error 
![Screenshot 2023-08-19 6 03 02 PM](https://github.com/duinoapp/duinoapp-client/assets/134627605/cac8b6f8-1d84-480a-b2d6-5a73facb76f2)
![Screenshot 2023-08-19 5 38 43 PM](https://github.com/duinoapp/duinoapp-client/assets/134627605/5a47163d-8a83-4866-873c-a436998204dd)

**Comment by mrfrase3** [comment]
Not entirely certain if this is causing the issue, but the Arduino mega cant act as a HID device. You need something with a ATmega32u4 chip, i.e. a pro micro or leonardo.

More annoyingly, the 32u4 chips require the AVR109 uploader that isn't supported on this version of the application.

**Comment by ghost** [comment]
> Not entirely certain if this is causing the issue, but the Arduino mega cant act as a HID device. You need something with a ATmega32u4 chip, i.e. a pro micro or leonardo.
> 
> More annoyingly, the 32u4 chips require the AVR109 uploader that isn't supported on this version of the application.

That might be the issue
